version: '3'

services:
  app-shop:
    build: shopFrontApiRest
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://shopAppDb:3306/shopAppApi?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234
      DB_PROFILE: production
      API_PORT: 8080
    restart: always
    depends_on:
      shopAppDb:
          condition: service_healthy
  shopAppDb:
    image: mysql:8.0.33 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: shopAppApi
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10


